### PR TITLE
Add a new benchmark, tuple-stress.

### PR DESCRIPTION
**Pull request by nnethercote**
This benchmark stresses the compiler in interesting ways and I think it's worth including.

The name follows existing precedent even though I don't much like that precedent, because it results in long names with common prefixes that are a pain to tab-complete :(

The time to compile with a trunk rust is 4.1s on my machine.

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I don't believe the precedent makes much sense either; I think renaming this to something more like "big array of tuples" (though possibly not "big" since IIRC there's another benchmark with that name). We can include the issue information and other metadata as comments in the makefile or in the main source; or introduce a README in each directory documenting why that test is there and what it's intended to test. It's possible we can later convert some of that information to something shown on the site itself, too.

**Comment by nnethercote** [comment]
Name ideas: "ost-stress", "tuple-stress"?

**Comment by Mark-Simulacrum** [comment]
"tuple-stress" sounds good to me. @nrc What do you think?

**Comment by nrc** [comment]
+1 for avoiding `issue...` prefixes. `big_array_of_tuples` would be fine by itself, or tuple_stress is fine too

**Comment by nnethercote** [comment]
Updated to "tuple-stress".

**Comment by Mark-Simulacrum** [comment]
Looks good to me. I can't r+ (no permissions), though.

**Pull request merged**
